function createfigure(zdata1)
%CREATEFIGURE(zdata1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 24-Nov-2020 07:09:14

% Create figure
figure1 = figure('Name',...
    'Tempo de Operação [30min] - Carga 10  - velocidade do vento 6.4 m/s');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.108898598973505 0.0966163433688085 0.69265848245249 0.828383656631192]);
hold(axes1,'on');

% Create surfb
surf(zdata1,'Parent',axes1);

% Create zlabel
zlabel('Energia despendida (kj)');

% Create ylabel
ylabel({'Probabiliade ','de existir','superfície','para pouso(%)',''},...
    'HorizontalAlignment','center');

% Create xlabel
xlabel({'Probabiliade ','de existir','prédios (%)',''},...
    'HorizontalAlignment','center');

% Create title
title('Tempo de operação [30 min] - Carga [10 kg]- vel vento [6.4 m/s]');

view(axes1,[-127.5 43.6]);
grid(axes1,'on');
% Create colorbar
colorbar('peer',axes1);

